// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Api {
  public static partial class API
  {
    static readonly string __ServiceName = "api.API";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Api.Client> __Marshaller_api_Client = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Api.Client.Parser));
    static readonly grpc::Marshaller<global::Api.Info> __Marshaller_api_Info = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Api.Info.Parser));
    static readonly grpc::Marshaller<global::Api.Request> __Marshaller_api_Request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Api.Request.Parser));
    static readonly grpc::Marshaller<global::Api.Update> __Marshaller_api_Update = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Api.Update.Parser));

    static readonly grpc::Method<global::Api.Client, global::Api.Info> __Method_GetInfo = new grpc::Method<global::Api.Client, global::Api.Info>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetInfo",
        __Marshaller_api_Client,
        __Marshaller_api_Info);

    static readonly grpc::Method<global::Api.Request, global::Api.Update> __Method_Track = new grpc::Method<global::Api.Request, global::Api.Update>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Track",
        __Marshaller_api_Request,
        __Marshaller_api_Update);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Api.ApiReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of API</summary>
    [grpc::BindServiceMethod(typeof(API), "BindService")]
    public abstract partial class APIBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Api.Info> GetInfo(global::Api.Client request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Track(grpc::IAsyncStreamReader<global::Api.Request> requestStream, grpc::IServerStreamWriter<global::Api.Update> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for API</summary>
    public partial class APIClient : grpc::ClientBase<APIClient>
    {
      /// <summary>Creates a new client for API</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public APIClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for API that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public APIClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected APIClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected APIClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Api.Info GetInfo(global::Api.Client request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Api.Info GetInfo(global::Api.Client request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetInfo, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Api.Info> GetInfoAsync(global::Api.Client request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Api.Info> GetInfoAsync(global::Api.Client request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetInfo, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Api.Request, global::Api.Update> Track(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Track(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Api.Request, global::Api.Update> Track(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Track, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override APIClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new APIClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(APIBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetInfo, serviceImpl.GetInfo)
          .AddMethod(__Method_Track, serviceImpl.Track).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, APIBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetInfo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Api.Client, global::Api.Info>(serviceImpl.GetInfo));
      serviceBinder.AddMethod(__Method_Track, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Api.Request, global::Api.Update>(serviceImpl.Track));
    }

  }
}
#endregion
